Added cronjob check

diff --git a/app/dockcheck b/app/dockcheck
--- a/app/dockcheck
+++ b/app/dockcheck
@@ -1,7 +1,7 @@
 #!/bin/bash
 /app/dockcheck.sh -n | sed -r "s:\x1B\[[0-9;]*[mK]::g" > /app/containers_temp
 cat /app/containers_temp > /app/containers
-echo "$(date). Cron ran without error." >> /var/log/cron.log
+#echo "$(date). Cron ran without error." >> /var/log/cron.log
 
 
 
@@ -33,3 +33,4 @@ if [ -f "$NOTIFY_URLS" ]; then
         fi
 fi
 
+#if [ $? -eq 0 ]; then echo "$(date). Cron ran without error." >> /var/log/cron.log ; else echo "$(date). Cron got errors." >> /var/log/cron.log ; fi
